version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file inTemplate.yaml --s3-bucket codepipeline-us-east-2-802118224578 --output-template-file outTemplate.yaml
artifacts:
  type: zip
  files:
    - inTemplate.yaml
    - outTemplate.yaml